version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"
    volumes:
      - .:/code
      - sqlite_data:/code/data
      - static_data:/code/static
    environment:
      - DJANGO_SETTINGS_MODULE=feedmaker.settings.docker
      - SECRET_KEY=${SECRET_KEY:-insecure_dev_key_change_in_production}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    restart: unless-stopped
    command: >
      bash -c "mkdir -p /code/data &&
               chmod 777 /code/data &&
               python manage.py migrate &&
               python manage.py collectstatic --noinput --clear &&
               gunicorn --bind :8000 --workers 2 --access-logfile - --preload feedmaker.wsgi"

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_data:/var/www/static
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    depends_on:
      - web
    restart: unless-stopped

volumes:
  sqlite_data:
  redis_data:
  static_data:
