version: '3.8'

services:
  web:
    container_name: feedmaker-web
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8001"  # Changed from 8000 to 8001
    volumes:
      # Instead of mounting the directory, we'll use the image's built-in code
      # and just mount the data and static directories for persistence
      - /storage/feedmaker/data:/code/data
      - /storage/feedmaker/static:/code/static
    environment:
      - DJANGO_SETTINGS_MODULE=feedmaker.settings.docker
      - SECRET_KEY=${SECRET_KEY:-insecure_dev_key_change_in_production}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    restart: unless-stopped
    command: >
      bash -c "mkdir -p /code/data &&
               chmod 777 /code/data &&
               python manage.py migrate &&
               python manage.py collectstatic --noinput --clear &&
               gunicorn --bind :8001 --workers 2 --access-logfile - --preload feedmaker.wsgi"  # Changed from 8000 to 8001

  redis:
    container_name: feedmaker-redis
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - /storage/feedmaker/redis-data:/data
    command: redis-server --save 60 1 --loglevel warning

  nginx:
    container_name: feedmaker-nginx
    image: nginx:1.25-alpine
    ports:
      - "7080:80"  # Using a very uncommon port (7080) to avoid conflicts
      - "7443:443"  # Using a very uncommon port (7443) to avoid conflicts
    volumes:
      - /storage/feedmaker/nginx/conf.d:/etc/nginx/conf.d
      # Removed the nginx.conf mount to use the default one in the container
      - /storage/feedmaker/static:/var/www/static
      - /storage/feedmaker/nginx/certbot/conf:/etc/letsencrypt
      - /storage/feedmaker/nginx/certbot/www:/var/www/certbot
    depends_on:
      - web
    restart: unless-stopped
