version: '3.8'

services:
  web:
    container_name: feedmaker-web
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"
    volumes:
      - .:/code
      - sqlite_data:/code/data
      - static_data:/code/static
    environment:
      - DJANGO_SETTINGS_MODULE=feedmaker.settings.docker
      - SECRET_KEY=${SECRET_KEY:-insecure_dev_key_change_in_production}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    command: >
      bash -c "mkdir -p /code/data &&
               chmod 777 /code/data &&
               python manage.py migrate &&
               python manage.py collectstatic --noinput --clear &&
               gunicorn --bind :8000 --workers 2 --access-logfile - --preload feedmaker.wsgi"
    networks:
      - feedmaker-network
    labels:
      - "com.docker.compose.project=feedmaker"
      - "com.docker.compose.service=web"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    container_name: feedmaker-redis
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - feedmaker-network
    labels:
      - "com.docker.compose.project=feedmaker"
      - "com.docker.compose.service=redis"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    container_name: feedmaker-nginx
    image: nginx:1.25-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_data:/var/www/static
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    depends_on:
      web:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - feedmaker-network
    labels:
      - "com.docker.compose.project=feedmaker"
      - "com.docker.compose.service=nginx"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

# Using default network to avoid Portainer network creation issues
networks:
  feedmaker-network:

# Using bind mounts instead of named volumes to avoid Portainer volume creation issues
volumes:
  sqlite_data:
  redis_data:
  static_data:
