# fly.toml file generated for feedmaker on 2023-03-10T13:09:43-06:00

app = "feedmaker"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "ord"
processes = []

[env]
  PORT = "8000"
  DJANGO_SETTINGS_MODULE = "feedmaker.settings.production"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
